### ISSUE TITLE
Is this a frontend to karabou.ch

### ISSUE THREAD

**Issue by woakes070048** [karibou-ch/kng2-core#34]

**Comment by evaletolab** [comment]
Yes, it will be a lib (kng2-core) plus an app (ng-test subdir) both helpers to create the next frontend UX. It's based on our practice with the first version. Would you like to help on it?

**Comment by woakes070048** [comment]
Yeah, i think i would like to. We are using have a instance of open food network right now. How complete is this would you say, so i could have an estimate on time to market for a local food hub that we are working with.

**Comment by evaletolab** [comment]
Sorry @woakes070048 , to answer you about the app coverage it depends on your needs! 
Karibou.ch is working as a platform (eg. airbnb) each farmers manages their store, stocks, customers, open/closed time, and orders. This actuel re-implementation of the frontend is not ready, but I will add a comment soon we get something testable.

**Comment by woakes070048** [comment]
okay so if i use the karibou.ch repo will it give me the same site as Karibou.ch? I only ask is we know we are going to need the software to be ready in about a month. we have this https://freshharvestcrate.com.
