### ISSUE TITLE
comprendre quel service (factory) est utilisé lors du load de l'application

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/kng2-core#4]
- rédiger une simple description en fonction de la vue debug de chrome/ff

**Comment by GonzalD** [comment]
Voir dans dev-console chrome les commandes: GET etc. et comprendre comme les services récupèrent et instancient les objets javascript

**Comment by GonzalD** [comment]
Poser les api des services angular 1 dans les services correspondant sur angular 2, compléter le wiki, commentaires et questions
