### ISSUE TITLE
implémenter un service de feedback AKA flash message

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/kng2-core#45]
* un service de message doit gérer le temps d'affichage
* le service de message est lié à un composant 
* il doit être utilisé pour chaque POST de chaques composants (save, delete, add)
* un dictionnaire par component doit contenir tous les messages (pour pouvoir migrer en i18n plus tard)
* chaque message doit être défini en majuscule, dans une classe Message
* la classe Message est définie et instanciée en haut de la classe qui l'utilise
La classe Message doit avoir cette forme
```js
class Message{
  USER_SAVE_DONE={fr:'Merci'};
}
//
// et sera utilisé comme ça
msg=new Message()
msg.USER_SAVE_DONE['fr']
// ici le string `fr` sera définit par i18n
```
Le service de message doit avoir cette forme
 // le temps de 4000 ms est optionnel
 // `this.$flash.message(this.msg.USER_SAVE_DONE,4000);`
 // `this.$flash.error(err,4000);`
 // c'est un observable (liste ou string ? ) qui sera écouté par le template (le $ a la fin signifie que c'est un stream)
 // `this.$flash.done$`
 // `this.$flash.error$`

**Comment by VallatMa** [comment]
Je ne comprend exactement à quoi servent les observable 
```// this.$flash.done$ // this.$flash.error$ ```

**Comment by evaletolab** [comment]
et bien tous le/les composant(s) qui auront besoins de notifier un message ou une erreur utilisent `this.$flash.done$.subscribe() `

Les autres composants utilisent un helper `this.$flash.message(this.msg.USER_SAVE_DONE,4000);` qui permet de gérer le timeout, etc... mais surtout d’émettre un event
