### ISSUE TITLE
créer un projet séparé pour l'application PWA panierlocal

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/kng2-core#60]
Je pense que tu dois créer un répo github séparer pour PWA, `ng-test` est la pour aider
* créer un projet github `kng2-pwa-panierlocal`
* faire `npm install kng2-core`
* faire une page README qui explique comment installer et compiler

**Comment by VallatMa** [comment]
qu'es-ce que tu penses de ce repo pour la base de la PWA ?
https://github.com/mgechev/angular-seed

**Comment by evaletolab** [comment]
je sais pas, je te propose de prendre ta branche pwa et d'en faire un projet. Ou tu avais une autre idée en tête?

**Comment by VallatMa** [comment]
Okay je vais faire ça comme ça alors au lieu d'utiliser un seed, j'ai trouvé de bon tuto pour setup un pwa depuis un client normal.
si tu veux jetter un coup d'oeil:
https://stormpath.com/blog/progressive-web-applications-angular-spring-boot-stormpath
